const Sdata = [
    {   id:1,
        imgsrc: "./PG.jpg",
        title: "The Founding Member",
        sname: "Prashant Gupta",
        link: "https://www.instagram.com/prashantlfh/",
    },
    {   id:2,
        imgsrc: "./Utsav.jpg",
        title: "The Member",
        sname: "Utsav Singh",
        link: "https://www.instagram.com/singh.utus/",

    },
    {   id:3,
        imgsrc: "./Yash.jpg",
        title: "The Founding Member",
        sname: "Yashpal Singh",
        link: "https://www.instagram.com/yash_singh_301/",
    },
    {   id:4,
        imgsrc: "./Naro.jpg",
        title: "The Founding Member",
        sname: "Narottam",
        link: "https://www.instagram.com/naro_ttam/",
    },
    {   id:5,
        imgsrc: "./Sachin.jpg",
        title: "The Founding Member",
        sname: "Sachin Kumar",
        link: "https://www.instagram.com/sach_in.15/",
    },
    {   id:6,
        imgsrc: "./Swapnil.jpg",
        title: "The Member",
        sname: "Swapnil Verma ",
        link: "https://www.instagram.com/neel.23797/",

    },
    
];
export default Sdata;